### ISSUE TITLE
[feat] Speaker identification 추가 및 모듈화

### ISSUE THREAD

**Issue by Somang-Kang** [Think-Tank-6/VOS-server#26]
## 📌 설명
> speaker identification model (Clova Speech AI) 추가 및 기능별 모듈화

## 🗒️ Todo
- [ ] ClovaSpeechClient 연결
- [ ] 인식된 화자별 음성 추출
- [ ] 선택된 화자의 음성만 추출 및 통합
- [ ] 음성파일 wav로 저장
