### ISSUE TITLE
[feat] 채팅 프롬프트 구현

### ISSUE THREAD

**Issue by Somang-Kang** [Think-Tank-6/VOS-server#34]
## 📌 설명
> 채팅 프롬프트 구현 및 기능별 모듈화

## 🗒️ Todo
- [ ] issue #30 에서 추출된 프롬프트와 system input 프롬프트 병합
- [ ] 사용자 이름, 성별, 호칭에 따른 프롬프트 동적 변형 가능하도록 구현
- [ ] 채팅 프롬프트 구현
